default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: 
          - flake8-builtins==2.5.0
          - flake8-docstrings==1.7.0
          - flake8-isort==6.1.1
          - flake8-pyproject==1.2.3

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
